namespace: purestorage
name: pure1
version: 1.5.0
readme: README.md
authors:
  - Everpure Ansible Team <pure-ansible-team@everpuredata.com>
description: Collection of modules to manage Everpure Pure1
license:
  - GPL-3.0-or-later
  - BSD-2-Clause
tags:
  - everpure
  - purestorage
  - pure1
  - storage
dependencies: {}
repository: https://github.com/Everpure-Ansible/Pure1-Collection
documentation: https://github.com/Everpure-Ansible/Pure1-Collection
issues: https://github.com/Everpure-Ansible/Pure1-Collection/issues
